Backend/nico/create sheet
BigSheet-org/BigSheet pull request #27
Opened 2023-11-20 16:11 UTC by QUEIGNEC

Faudra juste revoir pour les associations entre les modèles pour les mettre dans un fichier à part et pas dans UserModel car il faut charger les associations après la création de tout les modèles (méthode init).
Sinon tout fonctionne.

2023-11-20 17:20 UTC, Maximelego requested changes
Certaines choses doivent être modifiées.
Il faut notamment implémenter correctement les relations m2m avec les sheets.

2023-11-20 17:52 UTC, QUEIGNEC commented on backend/src/model/SheetModel.js
> +        let sheets = user.getOwned();
Si elle existe sinon ça fonctionnerai pas. Renseignes toi sur les alias dans les associations mais oui je vais changer le nom comme tu voulais au dessus.

2023-11-20 17:57 UTC, QUEIGNEC commented on backend/src/routes/sheets.js
> +        SheetController.getOwnedByUserId
Sauf que ça retourne tout les sheet dont l'utilisateur (id) a accès. Pas un sheet avec l'id voulu. Tu veux une route pour récupérer un Sheet avec son id ?

2023-11-20 17:59 UTC, QUEIGNEC commented on backend/src/routes/sheets.js
> +    .get('/me', [
C'était déjà fait avec delete... Pour la requête create y a pas de paramètre donc pas de Middleware

2023-11-20 18:08 UTC, Maximelego commented on backend/src/routes/sheets.js
> +    .get('/me', [
Tu n'as pas de paramètres dans create ?
Etrange. Tu devrais au moins mettre un paramètre optionnel pour le nom du document.
Delete, je n'ai pas vu de Middleware vérifiant que le paramètre id était bien renseigné.

2023-11-20 18:09 UTC, Maximelego commented on backend/src/routes/sheets.js
> +        SheetController.getOwnedByUserId
Oui fais les deux routes pour ça du coup ce sera mieux.

2023-11-20 19:20 UTC, QUEIGNEC commented on backend/src/model/UserModel.js
> +SheetModel.belongsTo(UserModel, {
Pour les associations, on est obligé de faire dans les 2 sens. Ici un belongsTo et un hasMany pour une relation Once to Many

2023-11-22 00:03 UTC, Maximelego requested changes
Quelques dernières choses à modifier. Le code pourra être merge après.

2023-11-22 00:03 UTC, Maximelego commented on backend/src/index.js
>  }
L'import des modèles est inutile. Tu peux retirer toute la boucle.
Tu le fais automatiquement à la ligne 62.

2023-11-22 00:03 UTC, Maximelego commented on backend/src/index.js
>  }
L'import des modèles est inutile. Tu peux retirer toute la boucle.
Tu le fais automatiquement à la ligne 62.

2023-11-22 00:03 UTC, Maximelego commented on backend/src/middleware/SheetMiddleware.js
> +    static async hasPermission(req, res, next) {
Renomme la en hasPermissionToDelete.

2023-11-22 10:45 UTC, QUEIGNEC commented on backend/src/index.js
>  }
Si il y a un modèle sans associations, il sera jamais importer et donc non initialiser.
L'import de User et Sheet se fait dans l'association ligne 57 et non 62

2023-11-22 10:47 UTC, QUEIGNEC commented on backend/src/routes/sheets.js
>      .get('/all', [
Il n'y a pas de droit d'accès sur cette PR. Je prend note pour la prochaine PR mais pour l'instant all=owned.

2023-11-22 10:49 UTC, QUEIGNEC commented on backend/src/routes/sheets.js
> +        SheetMiddleware.hasPermission,
J'ai mis hasPermission car c'est aussi utile pour le get('/:id'). Je rechangerai avec les différents droit d'accès prochaine PR.

2023-11-22 10:52 UTC, QUEIGNEC commented on backend/src/middleware/SheetMiddleware.js
> +    static async hasPermission(req, res, next) {
J'ai mis hasPermission car c'est aussi utile pour le get('/:id'). Je rechangerai avec les différents droit d'accès prochaine PR. Je ferai un hasPermissionAcces et hasPermissionDelete

2023-11-22 12:52 UTC, Maximelego requested changes

2023-11-22 12:52 UTC, Maximelego commented on backend/src/routes/users.js
> +        UserMiddleware.userExist,
La méthode n'est pas utile.
Il faut extraire l'id de l'utilisateur du token Impossible de créer un token si l'utilisateur n'existe pas.
Tu peux modifier checkAuthToken pour ajouter l'id de l'utilisateur dans le body de la request ;)

2023-11-22 13:01 UTC, Maximelego approved these changes

2023-11-22 13:01 UTC, merged