Clement/liste tableaux accueil
BigSheet-org/BigSheet pull request #32
Opened 2023-11-27 15:42 UTC by aildontknow

2023-11-27 21:07 UTC, Maximelego requested changes
Juste 1 changement demandé.

2023-12-12 15:45 UTC, Maximelego approved these changes

2023-12-13 13:13 UTC, QUEIGNEC requested changes

2023-12-13 13:13 UTC, QUEIGNEC commented on frontend/src/components/sheetlist/SheetList.vue
> +            return Routes
tu peux remettre un ;

2023-12-13 13:13 UTC, QUEIGNEC commented on frontend/src/components/sheetlist/SheetList.vue
> +            loading: false,
tu peux enlever la ,

2023-12-14 13:06 UTC, QUEIGNEC approved these changes

2023-12-14 16:00 UTC, merged