Backend/nico/sheet user m2m
BigSheet-org/BigSheet pull request #33
Opened 2023-11-27 22:22 UTC by QUEIGNEC

Tout fonctionne mais redis pour le format des données de Sheet qui sont renvoyer ça me plait pas trop. Au pire je referai une fonction pour reformater les données. Et est ce que je rajoute une description aux Sheets ? comme vous avez mis sur le front avec Clément

2023-11-28 10:47 UTC, Maximelego requested changes
Somme changes needs to be made.
This is a partial review. Changes will need another one.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/common/data/Data.js
> +            ACCESS_SHEET_INVALID: {"message": "Provided access not exist."}
euuuuh
Cette phrase ne veut pas dire grand chose. Veux tu plutôt dire que l'utilisateur n'a pas accès à la ressource ?

2023-11-28 10:47 UTC, Maximelego commented on backend/src/association/UserAccessSheet.js
> +        modelName: 'userAccessSheet'
Pourquoi est-ce que le nom du modèle commence par une minuscule ?

2023-11-28 10:47 UTC, Maximelego commented on backend/src/controllers/SheetController.js
> +     * This method will ask the model to get all sheets accessible by connected user.
Il faut ajouter une ligne vide après une description.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/controllers/SheetController.js
> +        let userID = await Tokens.getUserIdFromToken(req.body.additionnalParameters.authToken);
Le token doit être dans le Header, jamais dans le body.
Place plutôt l'user_id dans l'objet additionnal parameters.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/controllers/SheetController.js
> +     * This method grant access to a user.
Il faut ajouter une ligne vide après une description JSdoc.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/controllers/SheetController.js
> +     * Require checkAuthToken
Il faut ajouter une ligne vide après une description JSDoc.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/controllers/SheetController.js
> +     * Require Middleware sheetExists userExists.
Il faut ajouter une ligne vide après une description JSDoc.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/controllers/SheetController.js
> +        sheet.save();
Il faut await cette méthode.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/middleware/SheetMiddleware.js
> +     * Require Middleware sheetExists.
Il faut ajouter une ligne vide après une description JSDoc.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/routes/sheets.js
> +    .put('/addUser/:sheetId/:userId/:access?', [
Trop de paramètres dans la requête. Il serait mieux de passer par le body.

2023-11-28 10:47 UTC, Maximelego commented on backend/src/routes/sheets.js
> +    .delete('/deleteUser/:sheetId/:userId', [
Pas besoin de nommer cette route deleteUser, juste user fera du sens.
(la route serait delete : /sheet/user/:sheetId/:userId).

2023-11-28 10:47 UTC, Maximelego commented on backend/src/routes/users.js
> +    .delete('/delete/:userId', [
Pas besoin de nommer la route delete. 
Le nom de la méthode est suffisant.

2023-11-28 16:13 UTC, QUEIGNEC commented on backend/src/association/UserAccessSheet.js
> +        modelName: 'userAccessSheet'
Sans ça, dans l'objet Sheet, si tu veux accéder au droit d'accès d'un utilisateur faut faire sheet.users[0].**U**serAccessSheet.accessRight. Je trouve étrange de mettre une majuscule ici.

2023-11-28 16:40 UTC, QUEIGNEC commented on backend/src/routes/sheets.js
> +    .put('/addUser/:sheetId/:userId/:access?', [
C'est quoi le problème de passer par la requête et pas par le body ? Les 2 premiers paramètres sont obligatoires et le dernier facultatif. Je trouve plus simple de passer par la requête que de rajouter un body lorsqu'on fera l'appel depuis le front.

2023-11-29 21:55 UTC, Maximelego commented on backend/src/association/UserAccessSheet.js
> +        modelName: 'userAccessSheet'
Peut-être, mais c'est plus ta méthode d'accès que je trouve étrange. UserAccessSheet est censé être un objet non ? Un objet commence avec une majuscule.

2023-11-29 22:02 UTC, Maximelego approved these changes

2023-11-29 22:04 UTC, merged