Backend/maxime/refactor the code
BigSheet-org/BigSheet pull request #35
Opened 2023-12-02 08:17 UTC by Maximelego

Refactor Majeur du code.
Apporte de la simplification syntaxique ainsi que de l'amélioration du système de stockage des paramètres.
Contient également les améliorations suivantes : 
- Système de Logout faisant planter le serveur corrigé et fonctionnel.
- Amélioration des containers docker pour qu'ils soient plus simples à re-build en cas de modification sur le serveur NodeJS.
- Retrait d'appels répétitifs de fonction et stockage des valeurs pertinentes
- Ajout majeur de documentation.

2023-12-02 22:29 UTC, QUEIGNEC commented on backend/src/common/tools/Params.js
> +    static exportParamsToResLocale(req, res, next) {
Et tu stocks les paramètres dans la réponse envoyer par le serveur, accessible par le client https://www.geeksforgeeks.org/express-js-res-locals-property/ . Si on intercepte la réponse et qu'il y a des données sensibles en paramètre. Je te laisse imaginer...

2023-12-02 22:29 UTC, QUEIGNEC commented on backend/src/controllers/SheetController.js
> +        await sheet.removeUser(user);       // TODO : function is undefined
pourquoi le TODO?

2023-12-02 22:29 UTC, QUEIGNEC commented on backend/src/controllers/SheetController.js
> +        await sheet.addUser(user);      // TODO : Wrong number of args
Pourquoi le TODO?

2023-12-02 22:29 UTC, QUEIGNEC commented on backend/src/routes/sheets.js
> +    .get('/shared', [
T'as ajouté une route mais t'as pas fait le controleur qui correspond.

2023-12-02 22:29 UTC, QUEIGNEC commented on backend/src/routes/sheets.js
>      .put('/addUser/:sheetId/:userId/:access?', [
Donc on laisse les paramètres dans l'URL?

2023-12-02 22:29 UTC, QUEIGNEC commented on backend/src/routes/users.js
> +    .get('/search', [
Faudra faire le controleur

2023-12-03 14:13 UTC, Maximelego commented on backend/src/common/tools/Params.js
> +    static exportParamsToResLocale(req, res, next) {
Les paramètre locals ne sont pas transmis au client. Normalement, pas de risque avec ça.
![image](https://github.com/BigSheet-org/BigSheet/assets/70325779/15ef0cb2-9807-49f1-bdd8-bfc658cc156a)
https://stackoverflow.com/questions/70117182/can-res-locals-be-accessed-by-clients

Pour la question du Middleware, je ne sais pas trop : Seule une méthode est utilisée en ce sens.

2023-12-03 14:15 UTC, Maximelego commented on backend/src/controllers/SheetController.js
> +        await sheet.removeUser(user);       // TODO : function is undefined
La fonction removeUser n'est pas définie dans la classe SheetModel.
J'avais oublié ce TODO.

2023-12-03 14:16 UTC, Maximelego commented on backend/src/routes/sheets.js
> +    .get('/shared', [
En effet, je corrige ça.

2023-12-03 14:19 UTC, Maximelego commented on backend/src/routes/users.js
> +    .get('/search', [
En effet. Je m'en charge.

2023-12-06 16:18 UTC, QUEIGNEC commented on backend/src/model/SheetModel.js
> +        return await this.findByPk(userID, {
La pk d'un sheet c'est l'id du sheet, pas un userId

2023-12-06 16:18 UTC, QUEIGNEC commented on backend/src/model/UserModel.js
> +import SheetModel from "./SheetModel.js";
inutile

2023-12-06 16:18 UTC, QUEIGNEC commented on backend/src/routes/sheets.js
> -        SheetMiddleware.sheetExists,
Pourquoi t'as enlevé cette vérification ?

2023-12-07 22:57 UTC, QUEIGNEC requested changes

2023-12-07 22:57 UTC, QUEIGNEC commented on backend/src/association/UserAccessSheet.js
> +        modelName: 'UserAccessSheet'
> Si tu remets la majuscule, tu peux carrément supprimer cette ligne. Ca revient au même

2023-12-07 22:57 UTC, QUEIGNEC commented on backend/src/common/data/Data.js
> +            WRITE: "write",
tu peux virer la virgule

2023-12-07 22:57 UTC, QUEIGNEC commented on backend/src/model/SheetModel.js
> +                    [Op.or]: [
T'es sûr qu'il faut pas faire un autre where date through?

2023-12-07 22:57 UTC, QUEIGNEC commented on backend/src/index.js
> +app.use(Params.exportParamsToResLocale);                // For all routes we export the params to facilitate their processing.
Tu peux l'enlever, tu l'avais mis dans les middleware à chaque route

2023-12-07 22:57 UTC, QUEIGNEC commented on backend/src/middleware/Params.js
> +        console.log(req.sheetID)
poubelle

2023-12-07 22:57 UTC, QUEIGNEC commented on backend/src/middleware/SheetMiddleware.js
> +            && x.userAccessSheet.accessRight === Data.SERVER_COMPARISON_DATA.PERMISSIONS.OWNER)) {
Je pense qu'il faut mettre UserAccessSheet avec le u majuscule vu que t'as modifier le nom du modèle dans UserAccessSheet.js

2023-12-07 22:57 UTC, QUEIGNEC commented on backend/src/middleware/AuthMiddleware.js
> +        let data = await Tokens.verifyRefreshTokens(Params.getRequestParams(res).body.refresh_token);
Pourquoi body?

2023-12-07 23:12 UTC, Maximelego commented on backend/src/middleware/AuthMiddleware.js
> +        let data = await Tokens.verifyRefreshTokens(Params.getRequestParams(res).body.refresh_token);
Dans la requête de logout ou de refresh, les tokens sont placés dans le body. Il faut donc que j'aille les rechercher ici.

2023-12-08 16:41 UTC, Maximelego commented on backend/src/model/SheetModel.js
> +                    [Op.or]: [
Je comprends pas ce que tu essaie de dire xD

2023-12-10 14:36 UTC, QUEIGNEC requested changes

2023-12-10 14:36 UTC, QUEIGNEC commented on backend/src/middleware/Params.js
> +            Params.addLocalParam(res, {body: req.body});
Tu laisse la séparation des paramètres d'url et du body?

2023-12-10 14:36 UTC, QUEIGNEC commented on backend/src/middleware/SheetMiddleware.js
>      static async hasPermissionToAccess(req, res, next) {
T'as pas remis la fonction là, elle est vide

2023-12-10 22:05 UTC, QUEIGNEC approved these changes

2023-12-10 22:06 UTC, merged